@echo off
echo Installing python...
msiexec /i python-2.7.15.msi /qr
echo Installing pygame...
C:\Python27\Scripts\pip.exe install pygame
echo Installing numpy...
C:\Python27\Scripts\pip.exe install numpy
echo Installing opencv...
copy cv2.pyd C:\Python27\Lib\site-packages
echo Installation completed!
pause